Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 220

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Rakefile'

# New cops introduced in rubocop 0.81

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

# New cops introduced in rubocop 0.82

Style/ExponentialNotation:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# New cops introduced in rubocop 0.83
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

# New cops introduced in rubocop 0.84
Lint/DeprecatedOpenSSLConstant:
  Enabled: true

# New cops introduced in rubocop 0.85
Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true
  
Style/RedundantRegexpEscape:
  Enabled: true

# TODO : refactor
Metrics/ParameterLists:
  Max: 6

