name: Jarvis Gem

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Test on Ruby ${{ matrix.ruby_version }}, Rails ${{ matrix.rails_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 2.6.x
        rails_version:
          - "~> 5.2.0"
          - "~> 6.0.0"
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use ruby ${{ matrix.ruby_version }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: Run specs
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Build and test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
